version: "3.8"

services:
  app:
    image: python:3.12
    container_name: python_app
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: tail -f /dev/null
    networks:
      - qdrant_network  # Adicionado à mesma rede do Qdrant

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - qdrant_network  # Mantido na mesma rede

volumes:
  qdrant_data:

networks:
  qdrant_network:
    driver: bridge  # Usando a rede bridge
